/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Implementes.AbrirOSImplements;
import Implementes.DepartamentoImplements;
import Implementes.UsuarioImplements;
import Ordem_ServicoDAO.AbrirOSDAO;
import Ordem_ServicoDAO.DepartamentoDAO;
import Ordem_ServicoDAO.UsuarioDAO;
import java.util.List;
import javax.swing.JOptionPane;
import ordemservico.model.AbrirOrdemS;
import ordemservico.model.Departamento;
import ordemservico.model.Usuario;
import org.jdesktop.observablecollections.ObservableCollections;

/**
 *
 * @author andreas
 */
public class AbrirOrdemServico extends javax.swing.JFrame {

    

    /**
     * Creates new form AbrirOrdemServico
     */
    public AbrirOrdemServico() {
        initComponents();
        abrirOsDAO = new AbrirOSImplements();
        setAbrirOrdemS(new AbrirOrdemS(new Usuario()));
        
        
        
         UsuarioDAO usuarioOS = new UsuarioImplements();
        List<Usuario> usuarios = usuarioOS.buscarTodos();
        
        DepartamentoDAO departamentoOS = new DepartamentoImplements();
        List<Departamento> departamentos = departamentoOS.buscarDepartamentos();
       
         for(Usuario usuario: usuarios){
            jcbComboCodigoUsuario.addItem(usuario);
         }
         
         for(Departamento departamento: departamentos){
             jcbDepartamentoA.addItem(departamento);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jlbDataDescricao = new javax.swing.JLabel();
        jlbHoraDescricao = new javax.swing.JLabel();
        jlbCaracteristica = new javax.swing.JLabel();
        jlbNumeroDesc = new javax.swing.JLabel();
        jbtSalvar = new javax.swing.JButton();
        jlbCodigoUsuario = new javax.swing.JLabel();
        jlbProblema = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboPrioridade = new javax.swing.JComboBox();
        jlbNumeroOrdem = new javax.swing.JLabel();
        javax.swing.text.MaskFormatter maskData = null;
        try{
            maskData = new javax.swing.text.MaskFormatter("##/##/####");
        }

        catch(java.text.ParseException exc) {}
        jtfDataAbrirOS = new javax.swing.JFormattedTextField(maskData);
        javax.swing.text.MaskFormatter maskHora = null;
        try{
            maskHora = new javax.swing.text.MaskFormatter("##:##:##");
        }

        catch(java.text.ParseException exc) {}
        jtfHoraAbrirOS = new javax.swing.JFormattedTextField(maskHora);
        jlbCodigoDepartamentoA = new javax.swing.JLabel();
        jcbDepartamentoA = new javax.swing.JComboBox();
        jcbComboCodigoUsuario = new javax.swing.JComboBox();
        jbtFecharAbrirOS = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        jFormattedTextField1.setText("jFormattedTextField1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlbDataDescricao.setText("Data:");

        jlbHoraDescricao.setText("Hora:");

        jlbCaracteristica.setText("Caracteristica do Problema:");

        jlbNumeroDesc.setText("Número de Ordem de Serviço:");

        jbtSalvar.setText("Salvar");
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });

        jlbCodigoUsuario.setText("Codigo Usuário:");

        jlbProblema.setText("Fonte do Problema:");

        jLabel1.setText("Prioridade:");

        jComboPrioridade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Urgente", "Imediata", "Normal" }));

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${abrirOrdemS.prioridade}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jComboPrioridade);
        bindingGroup.addBinding(jComboBoxBinding);
        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${abrirOrdemS.prioridade}"), jComboPrioridade, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${abrirOrdemS.dataEntrada}"), jtfDataAbrirOS, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${abrirOrdemS.horaEntrada}"), jtfHoraAbrirOS, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jlbCodigoDepartamentoA.setText("Nome do Departamento:");

        jcbDepartamentoA.setRenderer(new ComboBoxRendererDepNome());

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${abrirOrdemS.departamento.nomeDepartamento}");
        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jcbDepartamentoA);
        bindingGroup.addBinding(jComboBoxBinding);

        jcbDepartamentoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDepartamentoAActionPerformed(evt);
            }
        });

        jcbComboCodigoUsuario.setRenderer(new ComboBoxRendererUsuario());

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${abrirOrdemS.usuario.codigoUsuario}");
        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jcbComboCodigoUsuario);
        bindingGroup.addBinding(jComboBoxBinding);

        jcbComboCodigoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbComboCodigoUsuarioActionPerformed(evt);
            }
        });

        jbtFecharAbrirOS.setText("Fechar");
        jbtFecharAbrirOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFecharAbrirOSActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Abrir Ordem de Serviço");

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${abrirOrdemS.numeroOrdem}"), jFormattedTextField2, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${abrirOrdemS.problema}"), jTextField1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${abrirOrdemS.caracteristica}"), jTextField2, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbCaracteristica)
                            .addComponent(jLabel1)
                            .addComponent(jlbProblema)
                            .addComponent(jlbHoraDescricao))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfDataAbrirOS, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jComboPrioridade, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtfHoraAbrirOS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                                    .addComponent(jTextField1))
                                .addGap(163, 163, 163))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbCodigoDepartamentoA)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlbDataDescricao)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jlbNumeroDesc)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(86, 86, 86))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jbtSalvar)
                                        .addGap(26, 26, 26)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtFecharAbrirOS)
                                    .addComponent(jlbNumeroOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbCodigoUsuario)
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbComboCodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcbDepartamentoA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(163, 163, 163))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbNumeroOrdem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbNumeroDesc)
                            .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbDataDescricao, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfDataAbrirOS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbHoraDescricao)
                            .addComponent(jtfHoraAbrirOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbProblema)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCaracteristica)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbComboCodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbCodigoUsuario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCodigoDepartamentoA)
                    .addComponent(jcbDepartamentoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSalvar)
                    .addComponent(jbtFecharAbrirOS))
                .addGap(26, 26, 26))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed
       
       abrirOsDAO.inserir(abrirOrdemS);
       
       JOptionPane.showMessageDialog(null, "Ordem de Serviço Salva com Sucesso");
       
       
      
       


    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jcbDepartamentoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDepartamentoAActionPerformed
        abrirOrdemS.setDepartamento((Departamento)jcbDepartamentoA.getSelectedItem());
    }//GEN-LAST:event_jcbDepartamentoAActionPerformed

    private void jcbComboCodigoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbComboCodigoUsuarioActionPerformed

        abrirOrdemS.setUsuario((Usuario) jcbComboCodigoUsuario.getSelectedItem());
    }//GEN-LAST:event_jcbComboCodigoUsuarioActionPerformed

    private void jbtFecharAbrirOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFecharAbrirOSActionPerformed

        
        if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja Fechar?", "ATENÇÂO ",
                javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();
        }
        
        
    }//GEN-LAST:event_jbtFecharAbrirOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbrirOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbrirOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbrirOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbrirOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbrirOrdemServico().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboPrioridade;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jbtFecharAbrirOS;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JComboBox jcbComboCodigoUsuario;
    private javax.swing.JComboBox jcbDepartamentoA;
    private javax.swing.JLabel jlbCaracteristica;
    private javax.swing.JLabel jlbCodigoDepartamentoA;
    private javax.swing.JLabel jlbCodigoUsuario;
    private javax.swing.JLabel jlbDataDescricao;
    private javax.swing.JLabel jlbHoraDescricao;
    private javax.swing.JLabel jlbNumeroDesc;
    private javax.swing.JLabel jlbNumeroOrdem;
    private javax.swing.JLabel jlbProblema;
    private javax.swing.JTextField jtfDataAbrirOS;
    private javax.swing.JTextField jtfHoraAbrirOS;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    private AbrirOrdemS abrirOrdemS;
    private AbrirOSDAO abrirOsDAO;
    private List<AbrirOrdemS> abrirOrdens;

    public AbrirOrdemS getAbrirOrdemS() {
        return abrirOrdemS;
    }

    public void setAbrirOrdemS(AbrirOrdemS abrirOrdemS) {
        AbrirOrdemS OrdemVelha = this.abrirOrdemS;
        this.abrirOrdemS = abrirOrdemS;
        firePropertyChange("abrirOrdemS", OrdemVelha, this.abrirOrdemS);
    }

    public List<AbrirOrdemS> getAbrirOrdens() {
        
        return abrirOrdens;
    }

    public void setAbrirOrdens(List<AbrirOrdemS> abrirOrdens) {
         List<AbrirOrdemS> OrdensVelhas = this.abrirOrdens;
        this.abrirOrdens = ObservableCollections.observableList(abrirOrdens);
        firePropertyChange("abrirOrdens", OrdensVelhas, this.abrirOrdemS);
    }

    
   
}
