/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Implementes.DepartamentoImplements;
import Implementes.UsuarioImplements;
import Ordem_ServicoDAO.DepartamentoDAO;
import Ordem_ServicoDAO.UsuarioDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ordemservico.model.Departamento;
import ordemservico.model.Usuario;
import org.jdesktop.observablecollections.ObservableCollections;

/**
 *
 * @author andreas
 */
public class cadastroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form cadastroUsuario
     */
    public cadastroUsuario() {
        initComponents();
        
        usuarioOS = new UsuarioImplements();
        setUsuario(new Usuario(new Departamento()));


        atualizaTabela();

        DepartamentoDAO departamentoOS = new DepartamentoImplements();
        List<Departamento> departamentos = departamentoOS.buscarDepartamentos();

      
        
        for (Departamento departamento : departamentos){
            jcbNomeDepartamentoCadastro.addItem(departamento);
        }



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jlbNomeCadastro = new javax.swing.JLabel();
        jlbCodigoUsuario = new javax.swing.JLabel();
        jtfCodigoCadastro = new javax.swing.JTextField();
        jbtSalvarCadastro = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbUsuarios = new javax.swing.JTable();
        jbtExcluir = new javax.swing.JButton();
        jlbNomeDCadastro = new javax.swing.JLabel();
        jcbNomeDepartamentoCadastro = new javax.swing.JComboBox();
        jbtFecharUsuario = new javax.swing.JButton();
        jlbCadastroUsuarios = new javax.swing.JLabel();
        jtfCodUser = new javax.swing.JFormattedTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlbNomeCadastro.setText("Código do Usuário:");

        jlbCodigoUsuario.setText("Nome do Usuário:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${usuario.nome}"), jtfCodigoCadastro, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jbtSalvarCadastro.setText("Salvar");
        jbtSalvarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarCadastroActionPerformed(evt);
            }
        });

        jtbUsuarios.setColumnSelectionAllowed(true);
        jtbUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${usuarios}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jtbUsuarios);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codigoUsuario}"));
        columnBinding.setColumnName("Código Usuário");
        columnBinding.setColumnClass(Long.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome Usuário");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${departamento.nomeDepartamento}"));
        columnBinding.setColumnName("Nome Departamento");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jtbUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbUsuarios);
        jtbUsuarios.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jbtExcluir.setText("Excluir");
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });

        jlbNomeDCadastro.setText("Nome Departamento:");

        jcbNomeDepartamentoCadastro.setRenderer(new ComboBoxRendererDepNome());

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${usuario.departamento.nomeDepartamento}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jcbNomeDepartamentoCadastro);
        bindingGroup.addBinding(jComboBoxBinding);

        jcbNomeDepartamentoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNomeDepartamentoCadastroActionPerformed(evt);
            }
        });

        jbtFecharUsuario.setText("Fechar");
        jbtFecharUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFecharUsuarioActionPerformed(evt);
            }
        });

        jlbCadastroUsuarios.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlbCadastroUsuarios.setText("Cadastro de Usuário");

        jtfCodUser.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${usuario.codigoUsuario}"), jtfCodUser, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtSalvarCadastro)
                                .addGap(31, 31, 31)
                                .addComponent(jbtExcluir)
                                .addGap(26, 26, 26)
                                .addComponent(jbtFecharUsuario))
                            .addComponent(jlbCadastroUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbCodigoUsuario)
                                    .addComponent(jlbNomeCadastro)
                                    .addComponent(jlbNomeDCadastro))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbNomeDepartamentoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfCodUser, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfCodigoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbCadastroUsuarios)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNomeCadastro)
                    .addComponent(jtfCodUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCodigoUsuario)
                    .addComponent(jtfCodigoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNomeDCadastro)
                    .addComponent(jcbNomeDepartamentoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSalvarCadastro)
                    .addComponent(jbtExcluir)
                    .addComponent(jbtFecharUsuario))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSalvarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarCadastroActionPerformed

        
        usuarioOS.inserirUser(usuario);


        atualizaTabela();
         JOptionPane.showMessageDialog(null, "Usuário Salvo com Sucesso");


    }//GEN-LAST:event_jbtSalvarCadastroActionPerformed

    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed

        usuarioOS.removerUser(usuario);

        atualizaTabela();
        
      

    }//GEN-LAST:event_jbtExcluirActionPerformed

    private void jtbUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbUsuariosMouseClicked

        if (evt.getClickCount() == 2) {
            setUsuario(usuarios.get(jtbUsuarios.getSelectedRow()));
            
        }
        atualizaTabela();

    }//GEN-LAST:event_jtbUsuariosMouseClicked

    private void jcbNomeDepartamentoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbNomeDepartamentoCadastroActionPerformed


        usuario.setDepartamento((Departamento) jcbNomeDepartamentoCadastro.getSelectedItem());

    }//GEN-LAST:event_jcbNomeDepartamentoCadastroActionPerformed

    private void jbtFecharUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFecharUsuarioActionPerformed

        
        if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja Fechar?", "ATENÇÂO ",
                javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();
        }
        
        
        
    }//GEN-LAST:event_jbtFecharUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroUsuario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtExcluir;
    private javax.swing.JButton jbtFecharUsuario;
    private javax.swing.JButton jbtSalvarCadastro;
    private javax.swing.JComboBox jcbNomeDepartamentoCadastro;
    private javax.swing.JLabel jlbCadastroUsuarios;
    private javax.swing.JLabel jlbCodigoUsuario;
    private javax.swing.JLabel jlbNomeCadastro;
    private javax.swing.JLabel jlbNomeDCadastro;
    private javax.swing.JTable jtbUsuarios;
    private javax.swing.JFormattedTextField jtfCodUser;
    private javax.swing.JTextField jtfCodigoCadastro;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
   
    private Usuario usuario;
    private UsuarioDAO usuarioOS;
    private List<Usuario> usuarios;

    private void atualizaTabela() {

        setUsuarios(usuarioOS.buscarTodos());

    }

    public List<Usuario> getUsuarios() {
        return usuarios;
    }

    public void setUsuarios(List<Usuario> usuarios) {
        List<Usuario> velhosUsuarios = this.usuarios;
        this.usuarios = ObservableCollections.observableList(usuarios);
        firePropertyChange("usuarios", velhosUsuarios, this.usuarios);
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        Usuario UsuarioVelho = this.usuario;
        this.usuario = usuario;
        firePropertyChange("usuario", UsuarioVelho, this.usuario);
    }
}
