/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Implementes.DepartamentoImplements;
import Ordem_ServicoDAO.DepartamentoDAO;
import java.util.List;
import javax.swing.JOptionPane;
import ordemservico.model.Departamento;
import org.jdesktop.observablecollections.ObservableCollections;

/**
 *
 * @author andreas
 */
public class CadastroDepartamento extends javax.swing.JFrame {

    /**
     * Creates new form CadastroDepartamento
     */
    public CadastroDepartamento() {
        initComponents();
        
        departamentoDao = new DepartamentoImplements();
        setDepartamento((new Departamento()));
        
        
             
              
        atualizaTabela();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jlbCodigoDepartamento = new javax.swing.JLabel();
        jlbNomeDepartamento = new javax.swing.JLabel();
        jbtSalvar = new javax.swing.JButton();
        jbtFecharCadastroDepartamento = new javax.swing.JButton();
        jbtExcluir = new javax.swing.JButton();
        jtfNomeDepartamento = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbDepartamentosT = new javax.swing.JTable();
        jlbCadastroDep = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlbCodigoDepartamento.setText("Código Departamento:");

        jlbNomeDepartamento.setText("Nome Departamento:");

        jbtSalvar.setText("Salvar");
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });

        jbtFecharCadastroDepartamento.setText("Fechar");
        jbtFecharCadastroDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFecharCadastroDepartamentoActionPerformed(evt);
            }
        });

        jbtExcluir.setText("Excluir");
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${departamento.nomeDepartamento}"), jtfNomeDepartamento, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jtfNomeDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeDepartamentoActionPerformed(evt);
            }
        });

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${departamentos}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jtbDepartamentosT);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codDepartamento}"));
        columnBinding.setColumnName("Cod Departamento");
        columnBinding.setColumnClass(Long.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nomeDepartamento}"));
        columnBinding.setColumnName("Nome Departamento");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jtbDepartamentosT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbDepartamentosTMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtbDepartamentosT);

        jlbCadastroDep.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlbCadastroDep.setText("Cadastro de Departamento");

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${departamento.codDepartamento}"), jFormattedTextField1, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtSalvar)
                        .addGap(46, 46, 46)
                        .addComponent(jbtExcluir)
                        .addGap(44, 44, 44)
                        .addComponent(jbtFecharCadastroDepartamento))
                    .addComponent(jlbCadastroDep)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbCodigoDepartamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbNomeDepartamento)
                        .addGap(18, 18, 18)
                        .addComponent(jtfNomeDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlbCadastroDep)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCodigoDepartamento)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNomeDepartamento)
                    .addComponent(jtfNomeDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSalvar)
                    .addComponent(jbtExcluir)
                    .addComponent(jbtFecharCadastroDepartamento))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed

        departamentoDao.insert(departamento);
        
        atualizaTabela();
        
        JOptionPane.showMessageDialog(null, "Departamento Salvo com Sucesso");
        
       
    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jbtFecharCadastroDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFecharCadastroDepartamentoActionPerformed

        
        if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja Fechar?", "ATENÇÂO ",
                javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();
        }


    }//GEN-LAST:event_jbtFecharCadastroDepartamentoActionPerformed

    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed

        departamentoDao.remove(departamento);
        
        atualizaTabela();
        
        
    }//GEN-LAST:event_jbtExcluirActionPerformed

    private void jtbDepartamentosTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbDepartamentosTMouseClicked

        
         if (evt.getClickCount() == 2) {
            setDepartamento(departamentos.get(jtbDepartamentosT.getSelectedRow()));
        }
        
    }//GEN-LAST:event_jtbDepartamentosTMouseClicked

    private void jtfNomeDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeDepartamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDepartamento().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtExcluir;
    private javax.swing.JButton jbtFecharCadastroDepartamento;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JLabel jlbCadastroDep;
    private javax.swing.JLabel jlbCodigoDepartamento;
    private javax.swing.JLabel jlbNomeDepartamento;
    private javax.swing.JTable jtbDepartamentosT;
    private javax.swing.JTextField jtfNomeDepartamento;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    
    private Departamento departamento;
    private DepartamentoDAO departamentoDao;
    private List<Departamento> departamentos;
    
     private void atualizaTabela() {

       setDepartamentos(departamentoDao.buscarDepartamentos());

    }

    public Departamento getDepartamento() {
        return departamento;
    }

    public void setDepartamento(Departamento departamento) {

        Departamento departamentoVelho = this.departamento;
        this.departamento = departamento;
        firePropertyChange("departamento", departamentoVelho, this.departamento);

    }

    public List<Departamento> getDepartamentos() {
        return departamentos;
    }

    public void setDepartamentos(List<Departamento> departamentos) {

        List<Departamento> velhosDepartamentos = this.departamentos;
        this.departamentos = ObservableCollections.observableList(departamentos);
        firePropertyChange("departamentos", velhosDepartamentos, this.departamentos);

    }
}
