/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Implementes.AbrirOSImplements;
import Implementes.FecharOSImplements;
import Implementes.UsuarioImplements;
import Ordem_ServicoDAO.AbrirOSDAO;
import Ordem_ServicoDAO.ConcluirOSDAO;
import Ordem_ServicoDAO.UsuarioDAO;
import java.util.List;
import javax.swing.JOptionPane;
import ordemservico.model.AbrirOrdemS;
import ordemservico.model.ConcluirOrdemS;
import ordemservico.model.Usuario;
import org.jdesktop.observablecollections.ObservableCollections;

/**
 *
 * @author andreas
 */
public class ConcluirOrdemServico extends javax.swing.JFrame {

    /**
     * Creates new form ConcluirOrdemServico
     */
    public ConcluirOrdemServico() {
        initComponents();
        concluirOSdao = new FecharOSImplements();
        setConcluirOS(new ConcluirOrdemS(new AbrirOrdemS()));




        AbrirOSDAO aberturadao = new AbrirOSImplements();
        List<AbrirOrdemS> aberturas = aberturadao.buscarOrdensServicos();



        for (AbrirOrdemS abrir : aberturas) {
            jcbComboNumeroOrdem.addItem(abrir);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        jlbNumeroConc = new javax.swing.JLabel();
        jlbDataConc = new javax.swing.JLabel();
        jlbHoraConc = new javax.swing.JLabel();
        jbtSalvar = new javax.swing.JButton();
        jcbComboNumeroOrdem = new javax.swing.JComboBox();
        javax.swing.text.MaskFormatter maskData2 = null;
        try{
            maskData2 = new javax.swing.text.MaskFormatter("##/##/####");
        }

        catch(java.text.ParseException exc) {}
        jtfDataFecharOS = new javax.swing.JFormattedTextField(maskData2);
        javax.swing.text.MaskFormatter maskHora2 = null;
        try{
            maskHora2 = new javax.swing.text.MaskFormatter("##:##:##");
        }

        catch(java.text.ParseException exc) {}
        jtfHoraFecharOS = new javax.swing.JFormattedTextField(maskHora2);
        jLabel1 = new javax.swing.JLabel();
        jbtFecharConcluir = new javax.swing.JButton();
        jlbConclusaoOrdens = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlbNumeroConc.setText("Número de Ordem de Serviço:");

        jlbDataConc.setText("Data:");

        jlbHoraConc.setText("Hora:");

        jbtSalvar.setText("Salvar");
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });

        jcbComboNumeroOrdem.setRenderer(new ComboBoxRendererNumeroOS());

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${concluirOS.numerOSC.numeroOrdem}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jcbComboNumeroOrdem);
        bindingGroup.addBinding(jComboBoxBinding);

        jcbComboNumeroOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbComboNumeroOrdemActionPerformed(evt);
            }
        });

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${concluirOS.dataConclusao}"), jtfDataFecharOS, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${concluirOS.horaConclusao}"), jtfHoraFecharOS, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel1.setText("Código de Conclusão:");

        jbtFecharConcluir.setText("Fechar");
        jbtFecharConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFecharConcluirActionPerformed(evt);
            }
        });

        jlbConclusaoOrdens.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlbConclusaoOrdens.setText("Conclusão de Ordens de Serviços");

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${concluirOS.codConclusao}"), jFormattedTextField1, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtSalvar)
                        .addGap(26, 26, 26)
                        .addComponent(jbtFecharConcluir))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbConclusaoOrdens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jlbDataConc)
                            .addComponent(jlbHoraConc)
                            .addComponent(jlbNumeroConc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfHoraFecharOS, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(jFormattedTextField1)
                            .addComponent(jtfDataFecharOS, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(jcbComboNumeroOrdem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbConclusaoOrdens)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbDataConc)
                    .addComponent(jtfDataFecharOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbHoraConc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfHoraFecharOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNumeroConc)
                    .addComponent(jcbComboNumeroOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSalvar)
                    .addComponent(jbtFecharConcluir))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed

        concluirOSdao.inserirConcluir(concluirOS);

        JOptionPane.showMessageDialog(null, "Conclusão Realizada com Sucesso");

    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jcbComboNumeroOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbComboNumeroOrdemActionPerformed


        concluirOS.setNumeroOrdem((AbrirOrdemS) jcbComboNumeroOrdem.getSelectedItem());
    }//GEN-LAST:event_jcbComboNumeroOrdemActionPerformed

    private void jbtFecharConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFecharConcluirActionPerformed


        if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja Fechar?", "ATENÇÂO ",
                javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();
        }



    }//GEN-LAST:event_jbtFecharConcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConcluirOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConcluirOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConcluirOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConcluirOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConcluirOrdemServico().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtFecharConcluir;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JComboBox jcbComboNumeroOrdem;
    private javax.swing.JLabel jlbConclusaoOrdens;
    private javax.swing.JLabel jlbDataConc;
    private javax.swing.JLabel jlbHoraConc;
    private javax.swing.JLabel jlbNumeroConc;
    private javax.swing.JTextField jtfDataFecharOS;
    private javax.swing.JTextField jtfHoraFecharOS;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    private ConcluirOrdemS concluirOS;
    private ConcluirOSDAO concluirOSdao;
    private List<ConcluirOrdemS> concluidas;

    public ConcluirOrdemS getConcluirOS() {
        return concluirOS;
    }

    public void setConcluirOS(ConcluirOrdemS concluirOS) {
        ConcluirOrdemS conclusaoVelha = this.concluirOS;
        this.concluirOS = concluirOS;
        firePropertyChange("concluirOS", conclusaoVelha, this.concluirOS);

    }

    public List<ConcluirOrdemS> getConcluidas() {
        return concluidas;
    }

    public void setConcluidas(List<ConcluirOrdemS> concluidas) {
        List<ConcluirOrdemS> conclusoesVelhas = this.concluidas;
        this.concluidas = ObservableCollections.observableList(concluidas);
        firePropertyChange("concluidas", conclusoesVelhas, this.concluidas);

    }
}
