/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Implementes.AbrirOSImplements;
import Ordem_ServicoDAO.AbrirOSDAO;
import Telas.Processamento;
import Telas.AbrirOrdemServico;
import java.util.List;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import ordemServicoConexao.conexaoUtilOS;
import ordemservico.model.AbrirOrdemS;

/**
 *
 * @author andreas
 */
public class Tela_Abertura extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Abertura
     */
    public Tela_Abertura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiCadastroUsuario = new javax.swing.JMenuItem();
        jmiCadastrarDepartamento = new javax.swing.JMenuItem();
        jmiAbrirOrdem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiProcessamento = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmiRelatorios = new javax.swing.JMenu();
        jmiVisualizarOrdens = new javax.swing.JMenuItem();
        jmeSair = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenuItem5.setText("jMenuItem5");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/logo3.png"))); // NOI18N

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\andreas\\Desktop\\Documents\\TI\\SEGUNDO ANO\\4º Periodo\\Prog. de Aplicativos\\OrdemServico\\ICONES\\7248_32x32.png")); // NOI18N
        jMenu1.setText("   Início   ");

        jmiCadastroUsuario.setIcon(new javax.swing.ImageIcon("C:\\Users\\andreas\\Desktop\\Documents\\TI\\SEGUNDO ANO\\4º Periodo\\Prog. de Aplicativos\\OrdemServico\\ICONES\\user_add.png")); // NOI18N
        jmiCadastroUsuario.setText("Cadastro de Usuário");
        jmiCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastroUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jmiCadastroUsuario);

        jmiCadastrarDepartamento.setIcon(new javax.swing.ImageIcon("C:\\Users\\andreas\\Desktop\\Documents\\TI\\SEGUNDO ANO\\4º Periodo\\Prog. de Aplicativos\\OrdemServico\\ICONES\\8596_16x16.png")); // NOI18N
        jmiCadastrarDepartamento.setText("Cadastro de Departamento");
        jmiCadastrarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarDepartamentoActionPerformed(evt);
            }
        });
        jMenu1.add(jmiCadastrarDepartamento);

        jmiAbrirOrdem.setIcon(new javax.swing.ImageIcon("C:\\Users\\andreas\\Desktop\\Documents\\TI\\SEGUNDO ANO\\4º Periodo\\Prog. de Aplicativos\\OrdemServico\\ICONES\\6208_32x32.png")); // NOI18N
        jmiAbrirOrdem.setText("Abrir Ordem de Serviço");
        jmiAbrirOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAbrirOrdemActionPerformed(evt);
            }
        });
        jMenu1.add(jmiAbrirOrdem);

        jMenuBar1.add(jMenu1);

        jMenu4.setIcon(new javax.swing.ImageIcon("C:\\Users\\andreas\\Desktop\\Documents\\TI\\SEGUNDO ANO\\4º Periodo\\Prog. de Aplicativos\\OrdemServico\\ICONES\\6226_32x32.png")); // NOI18N
        jMenu4.setText("Interação");

        jmiProcessamento.setIcon(new javax.swing.ImageIcon("C:\\Users\\andreas\\Desktop\\Documents\\TI\\SEGUNDO ANO\\4º Periodo\\Prog. de Aplicativos\\OrdemServico\\ICONES\\Processamento.png")); // NOI18N
        jmiProcessamento.setText("Processamento da Ordem de Serviço");
        jmiProcessamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProcessamentoActionPerformed(evt);
            }
        });
        jMenu4.add(jmiProcessamento);

        jMenuBar1.add(jMenu4);

        jMenu8.setIcon(new javax.swing.ImageIcon("C:\\Users\\andreas\\Desktop\\Documents\\TI\\SEGUNDO ANO\\4º Periodo\\Prog. de Aplicativos\\OrdemServico\\ICONES\\7171_128x128.png")); // NOI18N
        jMenu8.setText("Conclusão");

        jMenuItem2.setIcon(new javax.swing.ImageIcon("C:\\Users\\andreas\\Desktop\\Documents\\TI\\SEGUNDO ANO\\4º Periodo\\Prog. de Aplicativos\\OrdemServico\\ICONES\\6176_32x32.png")); // NOI18N
        jMenuItem2.setText("Concluir Ordem de Serviço");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem2);

        jMenuBar1.add(jMenu8);

        jmiRelatorios.setIcon(new javax.swing.ImageIcon("C:\\Users\\andreas\\Desktop\\Documents\\TI\\SEGUNDO ANO\\4º Periodo\\Prog. de Aplicativos\\OrdemServico\\ICONES\\7175_128x128.png")); // NOI18N
        jmiRelatorios.setText("Visualização");

        jmiVisualizarOrdens.setIcon(new javax.swing.ImageIcon("C:\\Users\\andreas\\Desktop\\Documents\\TI\\SEGUNDO ANO\\4º Periodo\\Prog. de Aplicativos\\OrdemServico\\ICONES\\pedido.png")); // NOI18N
        jmiVisualizarOrdens.setText("Relatórios");
        jmiVisualizarOrdens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVisualizarOrdensActionPerformed(evt);
            }
        });
        jmiRelatorios.add(jmiVisualizarOrdens);

        jMenuBar1.add(jmiRelatorios);

        jmeSair.setIcon(new javax.swing.ImageIcon("C:\\Users\\andreas\\Desktop\\Documents\\TI\\SEGUNDO ANO\\4º Periodo\\Prog. de Aplicativos\\OrdemServico\\ICONES\\door_out.png")); // NOI18N
        jmeSair.setText("  Sair  ");
        jmeSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmeSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmeSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAbrirOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAbrirOrdemActionPerformed

        new AbrirOrdemServico().setVisible(true);
    }//GEN-LAST:event_jmiAbrirOrdemActionPerformed

    private void jmiCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastroUsuarioActionPerformed


        new cadastroUsuario().setVisible(true);
    }//GEN-LAST:event_jmiCadastroUsuarioActionPerformed

    private void jmiProcessamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProcessamentoActionPerformed

        new Processamento().setVisible(true);
    }//GEN-LAST:event_jmiProcessamentoActionPerformed

    private void jmeSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmeSairMouseClicked

        if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja Sair?", "ATENÇÂO ",
                javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_jmeSairMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed


        new ConcluirOrdemServico().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmiCadastrarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarDepartamentoActionPerformed

         new CadastroDepartamento().setVisible(true);

    }//GEN-LAST:event_jmiCadastrarDepartamentoActionPerformed

    private void jmiVisualizarOrdensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVisualizarOrdensActionPerformed

        new VisualizarRelatorios().setVisible(true);
        
        
    }//GEN-LAST:event_jmiVisualizarOrdensActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Abertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Abertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Abertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Abertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Abertura().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenu jmeSair;
    private javax.swing.JMenuItem jmiAbrirOrdem;
    private javax.swing.JMenuItem jmiCadastrarDepartamento;
    private javax.swing.JMenuItem jmiCadastroUsuario;
    private javax.swing.JMenuItem jmiProcessamento;
    private javax.swing.JMenu jmiRelatorios;
    private javax.swing.JMenuItem jmiVisualizarOrdens;
    // End of variables declaration//GEN-END:variables
}
