/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import ordemServicoConexao.conexaoUtilOS;

/**
 *
 * @author andreas
 */
public class VisualizarRelatorios extends javax.swing.JFrame {

    /**
     * Creates new form VisualizarRelatorios
     */
    public VisualizarRelatorios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbtRelatoriosUsuarios = new javax.swing.JButton();
        jbtRelatoriosOrdensAbertas = new javax.swing.JButton();
        jbtRelatoriosOrdensConc = new javax.swing.JButton();
        jbtFecharRelatórios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Relatórios");

        jLabel2.setText("Usuários:");

        jLabel3.setText("Ordens de Serviços Abertas:");

        jLabel4.setText("Ordens de Serviços Concluídas:");

        jbtRelatoriosUsuarios.setText("Visualizar");
        jbtRelatoriosUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRelatoriosUsuariosActionPerformed(evt);
            }
        });

        jbtRelatoriosOrdensAbertas.setText("Visualizar");
        jbtRelatoriosOrdensAbertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRelatoriosOrdensAbertasActionPerformed(evt);
            }
        });

        jbtRelatoriosOrdensConc.setText("Visualizar");
        jbtRelatoriosOrdensConc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRelatoriosOrdensConcActionPerformed(evt);
            }
        });

        jbtFecharRelatórios.setText("Fechar");
        jbtFecharRelatórios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFecharRelatóriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtRelatoriosOrdensConc)
                            .addComponent(jbtRelatoriosOrdensAbertas)
                            .addComponent(jbtRelatoriosUsuarios))))
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtFecharRelatórios)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jbtRelatoriosUsuarios))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jbtRelatoriosOrdensAbertas))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jbtRelatoriosOrdensConc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jbtFecharRelatórios)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtFecharRelatóriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFecharRelatóriosActionPerformed

        
        
        
        
        if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja Fechar?", "ATENÇÂO ",
                javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_jbtFecharRelatóriosActionPerformed

    private void jbtRelatoriosUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRelatoriosUsuariosActionPerformed

          
       try {
            JasperPrint jasperPrint = 
                    JasperFillManager.fillReport("C:/Users/andreas/Desktop/Documents/TI/SEGUNDO_ANO/4_Periodo/Prog. de Aplicativos/RelatorioOrdemDeServico/src/report/"
                    + "RelatorioUsers.jasper", 
                    null, new conexaoUtilOS().criarConexao());
            JasperViewer.viewReport(jasperPrint);  
        } catch (JRException ex) {
            System.out.println(ex.getMessage());
        }
    
        
        
        
    }//GEN-LAST:event_jbtRelatoriosUsuariosActionPerformed

    private void jbtRelatoriosOrdensAbertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRelatoriosOrdensAbertasActionPerformed

          try {
            JasperPrint jasperPrint = 
                    JasperFillManager.fillReport("C:/Users/andreas/Desktop/Documents/TI/SEGUNDO_ANO/4_Periodo/Prog. de Aplicativos/RelatorioOrdemDeServico/src/report/"
                    + "RelatorioAberturaOrdem.jasper", 
                    null, new conexaoUtilOS().criarConexao());
            JasperViewer.viewReport(jasperPrint);  
        } catch (JRException ex) {
            System.out.println(ex.getMessage());
        }
        
        
    }//GEN-LAST:event_jbtRelatoriosOrdensAbertasActionPerformed

    private void jbtRelatoriosOrdensConcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRelatoriosOrdensConcActionPerformed

         try {
            JasperPrint jasperPrint = 
                    JasperFillManager.fillReport("C:/Users/andreas/Desktop/Documents/TI/SEGUNDO_ANO/4_Periodo/Prog. de Aplicativos/RelatorioOrdemDeServico/src/report/"
                    + "RelatorioConcluir.jasper", 
                    null, new conexaoUtilOS().criarConexao());
            JasperViewer.viewReport(jasperPrint);  
        } catch (JRException ex) {
            System.out.println(ex.getMessage());
        }
        
        
        
        
    }//GEN-LAST:event_jbtRelatoriosOrdensConcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizarRelatorios().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtFecharRelatórios;
    private javax.swing.JButton jbtRelatoriosOrdensAbertas;
    private javax.swing.JButton jbtRelatoriosOrdensConc;
    private javax.swing.JButton jbtRelatoriosUsuarios;
    // End of variables declaration//GEN-END:variables
}
